name: Test CICD
on:
  push:
    branches: 
      - main
    #paths-ignore:
    #  - '.github/workflows/*' 
  workflow_dispatch:

jobs:
  
  BUILD:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: printing hello 
        run: echo "Starting the Building job"
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Printling ls
        run: ls
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21
      - name: run test
        run: go test
      - name: Build the code
        run: go build -o app
      - name: print inside of the folder
        run: ls
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
      - name: store name exec in output
        id: publish
        run: find app echo 'script-file={}' >> GITHUB_OUTPUT ';'
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: .

  DOWNLOAD_ARTIFACT:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - name: Download previous build artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: app
          path: .
      - name: output filename from previous job
        run: echo "${{ needs.BUILD.outputs.script-file }}"
        
          
  SECOND_TEST:
    needs: DOWNLOAD_ARTIFACT
    runs-on: ubuntu-latest
    steps:
      - name: running some other command
        run: |
          echo "starting the script"
          MY_VAR="Hello World"
          if [ MY_VAR=="Hello World" ]; then
            echo "VAR IS CORRECT SET"
            echo "value of VAR is $MY_VAR"
          else
            echo "VAR IS NOT SET CORRECTLY"
            echo "value of VAR is $MY_VAR"
          fi
      - name: output filename from previous job
        run: echo "${{ needs.BUILD.outputs.script-file }}"
    
