name: test cicd
on:
  push:
    branches: main
  workflow_call:

jobs:
  
  TEST:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello 
        run: |
          echo "hello-world"
          echo "second hello"
